// Generated by CoffeeScript 1.6.3
(function() {
  var hello;

  hello = function(target) {
    if (target == null) {
      target = "world";
    }
    return "hello " + target;
  };

  console.log(hello(null));

}).call(this);
